name: Lint server

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: build (v22.15.1)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: v22.15.1
          cache: pnpm
      - name: Run lint
        run: |
          pnpm install --frozen-lockfile
          pnpm lint
        env:
          CI: true
